# Node
lbl_country = "Country"
lbl_instance = "Instance"
lbl_ip = "IP"
lbl_region = "Region"
lbl_sapsid = "SapSid"
lbl_server = "Server"
lbl_site = "Site"
lbl_softName = "softName"
lbl_softVersion = "softVersion"
lbl_solcomp = "SolComp"
lbl_solinstcomp = "SolInstComp"
lbl_solution = "Solution"
lbl_vendor = "Vendor"
lbl_wave = "Wave"

# Relations
instance2solinstcomp = "toInstComp"
instance2softVersion = "isVersion"
parent2server = "hasVirtual"
server2instance = "serverInst"
server2ip = "hasIP"
server2server = "hasVirtual"
site2country = "inCountry"
site2region = "inRegion"
site2server = "hasDev"
softName2vendor = "fromVendor"
softVersion2name = "isSoft"
solcomp2sap = "inSid"
solcomp2solution = "fromSolution"
solinstcomp2solcomp = "toComponent"
solution2solution = "sol2sol"
solution2wave = "inWave"
